# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lOADING.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QWidget{\n"
"    background-color:rgb(255, 189, 145);\n"
"    border-radius:12px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Logo = QtWidgets.QFrame(self.centralwidget)
        self.Logo.setMinimumSize(QtCore.QSize(200, 200))
        self.Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Logo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoimage = QtWidgets.QLabel(self.Logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoimage.sizePolicy().hasHeightForWidth())
        self.logoimage.setSizePolicy(sizePolicy)
        self.logoimage.setMinimumSize(QtCore.QSize(100, 100))
        self.logoimage.setMaximumSize(QtCore.QSize(100, 100))
        self.logoimage.setStyleSheet("QLabel{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:50px;\n"
"}")
        self.logoimage.setText("")
        self.logoimage.setPixmap(QtGui.QPixmap("icons/pizza_logo.png"))
        self.logoimage.setScaledContents(True)
        self.logoimage.setAlignment(QtCore.Qt.AlignCenter)
        self.logoimage.setObjectName("logoimage")
        self.horizontalLayout.addWidget(self.logoimage)
        self.verticalLayout.addWidget(self.Logo)
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.app_name = QtWidgets.QLabel(self.background)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.verticalLayout_2.addWidget(self.app_name)
        self.label = QtWidgets.QLabel(self.background)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Progress = QtWidgets.QFrame(self.background)
        self.Progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Progress.setObjectName("Progress")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Progress)
        self.verticalLayout_3.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.percentage = QtWidgets.QLabel(self.Progress)
        self.percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.percentage.setObjectName("percentage")
        self.verticalLayout_3.addWidget(self.percentage)
        self.progressBar = QtWidgets.QProgressBar(self.Progress)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background:rgb(255, 241, 123);\n"
"    border-style:none;\n"
"    border-radius:5px;\n"
"    color:rgb(20, 180, 250);\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(253, 255, 148, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.Progress)
        self.Footer = QtWidgets.QFrame(self.background)
        self.Footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addWidget(self.Footer)
        self.verticalLayout.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_name.setText(_translate("MainWindow", "PIZAA MANAGEMENT"))
        self.label.setText(_translate("MainWindow", "De Bezt Fizza In Da World"))
        self.percentage.setText(_translate("MainWindow", "24%"))


